/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.enea.diej01v2.vista;

import com.enea.diej01v2.controlador.Controlador;
import com.enea.diej01v2.modelo.DataAcces;


/**
 *
 * @author Enea
 */
public class Principal extends javax.swing.JFrame {
    public DataAcces da;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setSize(1200, 800);
        this.setLocationRelativeTo(null);
        txtNombre.setText("TEST");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        pnlMisAlojamientos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMisAlojamientos = new javax.swing.JTable();
        pnlFotos = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtPlazas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnListarAlojamientos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 800));

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlBg.setLayout(null);

        pnlMisAlojamientos.setBackground(new java.awt.Color(255, 255, 255));
        pnlMisAlojamientos.setBorder(javax.swing.BorderFactory.createTitledBorder("Mis alojamientos:"));

        tblMisAlojamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "DIRECCION", "MUNICIPIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMisAlojamientos.setGridColor(new java.awt.Color(255, 255, 255));
        tblMisAlojamientos.setSelectionBackground(new java.awt.Color(0, 153, 255));
        jScrollPane1.setViewportView(tblMisAlojamientos);

        javax.swing.GroupLayout pnlMisAlojamientosLayout = new javax.swing.GroupLayout(pnlMisAlojamientos);
        pnlMisAlojamientos.setLayout(pnlMisAlojamientosLayout);
        pnlMisAlojamientosLayout.setHorizontalGroup(
            pnlMisAlojamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMisAlojamientosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMisAlojamientosLayout.setVerticalGroup(
            pnlMisAlojamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMisAlojamientosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pnlBg.add(pnlMisAlojamientos);
        pnlMisAlojamientos.setBounds(20, 90, 550, 290);

        pnlFotos.setBorder(javax.swing.BorderFactory.createTitledBorder("Fotos"));

        javax.swing.GroupLayout pnlFotosLayout = new javax.swing.GroupLayout(pnlFotos);
        pnlFotos.setLayout(pnlFotosLayout);
        pnlFotosLayout.setHorizontalGroup(
            pnlFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        pnlFotosLayout.setVerticalGroup(
            pnlFotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );

        pnlBg.add(pnlFotos);
        pnlFotos.setBounds(20, 390, 550, 230);

        pnlDatos.setBackground(new java.awt.Color(255, 255, 255));
        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        pnlDatos.setLayout(null);

        jLabel1.setText("ID:");
        pnlDatos.add(jLabel1);
        jLabel1.setBounds(30, 30, 30, 20);

        txtId.setEnabled(false);
        pnlDatos.add(txtId);
        txtId.setBounds(60, 30, 64, 22);

        jLabel2.setText("Nombre:");
        pnlDatos.add(jLabel2);
        jLabel2.setBounds(150, 30, 50, 20);

        txtNombre.setEnabled(false);
        pnlDatos.add(txtNombre);
        txtNombre.setBounds(210, 30, 260, 22);

        jLabel3.setText("Dirección:");
        pnlDatos.add(jLabel3);
        jLabel3.setBounds(30, 70, 60, 20);

        txtDireccion.setEnabled(false);
        pnlDatos.add(txtDireccion);
        txtDireccion.setBounds(100, 70, 370, 22);

        jLabel4.setText("Descripcion:");
        pnlDatos.add(jLabel4);
        jLabel4.setBounds(30, 150, 90, 20);

        txtMunicipio.setEnabled(false);
        txtMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMunicipioActionPerformed(evt);
            }
        });
        pnlDatos.add(txtMunicipio);
        txtMunicipio.setBounds(100, 110, 370, 22);

        jLabel5.setText("Municipio:");
        pnlDatos.add(jLabel5);
        jLabel5.setBounds(30, 110, 60, 20);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setEnabled(false);
        jScrollPane2.setViewportView(txtDescripcion);

        pnlDatos.add(jScrollPane2);
        jScrollPane2.setBounds(30, 180, 440, 86);

        jLabel6.setText("Plazas:");
        pnlDatos.add(jLabel6);
        jLabel6.setBounds(30, 290, 40, 20);

        txtPlazas.setEnabled(false);
        pnlDatos.add(txtPlazas);
        txtPlazas.setBounds(80, 290, 71, 22);

        jLabel7.setText("Precio por noche:");
        pnlDatos.add(jLabel7);
        jLabel7.setBounds(170, 290, 100, 20);

        txtPrecio.setEnabled(false);
        pnlDatos.add(txtPrecio);
        txtPrecio.setBounds(280, 290, 71, 22);

        btnNuevo.setText("Nuevo");
        pnlDatos.add(btnNuevo);
        btnNuevo.setBounds(20, 360, 90, 23);

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        pnlDatos.add(btnGuardar);
        btnGuardar.setBounds(380, 360, 90, 23);

        btnModificar.setText("Modificar");
        pnlDatos.add(btnModificar);
        btnModificar.setBounds(120, 360, 90, 23);

        pnlBg.add(pnlDatos);
        pnlDatos.setBounds(590, 40, 490, 400);

        btnListarAlojamientos.setText("Listar");
        pnlBg.add(btnListarAlojamientos);
        btnListarAlojamientos.setBounds(30, 60, 160, 23);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Comentarios"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        pnlBg.add(jPanel1);
        jPanel1.setBounds(590, 450, 490, 170);

        btnLogin.setText("Login");
        pnlBg.add(btnLogin);
        btnLogin.setBounds(260, 60, 130, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMunicipioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Principal principal = new Principal();
        Controlador controlador = new Controlador(principal);
        principal.setVisible(true);
        principal.setLocationRelativeTo(null);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnListarAlojamientos;
    public javax.swing.JButton btnLogin;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlFotos;
    private javax.swing.JPanel pnlMisAlojamientos;
    public javax.swing.JTable tblMisAlojamientos;
    public javax.swing.JTextArea txtDescripcion;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtMunicipio;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPlazas;
    public javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
